accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('registration/', views.registration_view, name='registration'),
    
    # Add other URLs for admin, organizer, and attendee dashboards
]

admin_panel/urls.py
from django.urls import path
from . import views


app_name = 'admin_panel'

urlpatterns = [
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('events/', views.events_view, name='events'),
    path('events/create_event/', views.create_event, name='create_event'),
    path('events/<int:event_id>/edit_event/', views.edit_event_view, name='edit_event'),
    path('events/<int:event_id>/delete/', views.delete_event, name='event_delete'),
    path('event_categories/', views.event_categories_view, name='event_categories'), 
    path('event_categories/create_category/', views.create_category, name='create_category'),
    path('event_categories/<int:category_id>/edit_category/', views.edit_category, name='edit_category'),
    path('event_categories/<int:category_id>/delete_category/', views.delete_category, name='delete_category'),
    path('users/', views.users_view, name='users'),
    path('users/create_user/', views.create_user, name='create_user'),
    path('users/<int:user_id>/edit_user/', views.edit_user, name='edit_user'),
    path('users/<int:user_id>/delete_user/', views.delete_user, name='delete_user'),
    path('event_organizers/', views.event_organizers_view, name='event_organizers'),
    path('event_organizers/create_organizer/', views.create_organizer, name='create_organizer'),
    path('event_organizers/<int:organizer_id>/edit_organizer/', views.edit_organizer, name='edit_organizer'),
    path('event_organizers/<int:organizer_id>/delete_organizer/', views.delete_organizer, name='delete_organizer')
]

event_organizer/urls.py
from django.urls import path
from . import views

def is_event_organizer(user):
    return user.user_type == 'organizer'

app_name = 'event_organizer'

urlpatterns = [
    path('organizer_dashboard/', views.dashboard_view, name='dashboard'),
    path('organizer_events/', views.events_view, name='organizer_events'),
    path('events/create_event/', views.create_event, name='create_event'),
    path('events/<int:event_id>/edit_event/', views.edit_event, name='edit_event'),
    path('events/<int:event_id>/delete/', views.delete_event, name='event_delete'),
    path('attendees/', views.attendees_view, name='attendees')
]

eventsphere/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_panel/', include('admin_panel.urls')),
    path('accounts/', include('accounts.urls')),
    path('event_organizer/', include('event_organizer.urls')),
    path('eventsphere/', include('attendee.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

event_organizer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField


class Attendee(models.Model):
    ATTENDANCE_CHOICES = [
        ('attended', 'Attended'),
        ('not_attended', 'Not Attended'),
    ]
    attendee = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    event = models.ForeignKey('admin_panel.Event', on_delete=models.CASCADE,related_name='event_organizer_attendees')
    status = models.CharField(max_length=20, choices=ATTENDANCE_CHOICES, default='not_attended')
    name = models.CharField(max_length=100)  
    phone_number = PhoneNumberField()

    def __str__(self):
        return f"{self.attendee.username} - {self.event.name}"

event_organizer/forms.py
from django import forms
from admin_panel.models import Event
from accounts.models import CustomUser

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'description', 'event_category', 'location', 'date_time', 'image','ticket_type', 'ticket_price']

class EditEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'description', 'event_category', 'location', 'date_time', 'image','ticket_type', 'ticket_price']
        widgets = {
            'date_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }
        labels = {
            'ticket_type': 'Registration Type',
            'ticket_price': 'Registration Fee',
        }

event_organizer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from admin_panel.models import Event
from .models import  Attendee
from django.utils import timezone
from .forms import EventForm,EditEventForm
from admin_panel.models import EventCategory
from accounts.models import CustomUser

# Views for Event Organizer Dashboard
def dashboard_view(request):
    # Retrieve data for the dashboard for the logged-in event organizer
    logged_in_organizer = request.user
    total_events = Event.objects.filter(organizer=logged_in_organizer).count()
    total_completed_events = Event.objects.filter(organizer=logged_in_organizer, date_time__lt=timezone.now()).count()
    total_attendees = Attendee.objects.filter(event__organizer=logged_in_organizer).count()
    latest_events = Event.objects.filter(organizer=logged_in_organizer).order_by('-date_time')[:5]

    # Pass data to the template
    context = {
        'total_events': total_events,
        'total_completed_events': total_completed_events,
        'total_attendees': total_attendees,
        'latest_events': latest_events,
        'active_page': 'dashboard'
    }
    return render(request, 'organizer_base.html', context)

# Function to retrieve events
def events_view(request):
    all_events = Event.objects.all()
    return render(request, 'organizer_events.html', {'active_page': 'events', 'all_events': all_events})

def create_event(request):
    event_categories = EventCategory.objects.all()  # Retrieve all event categories
    attendees = CustomUser.objects.all()  # Retrieve all attendees
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        event = form.save(commit=False)
        event.organizer = request.user
        event.save()
        form.save_m2m()
            
            # Handle attendees field
        attendee_ids = request.POST.getlist('attendees')
        event.attendees.set(attendee_ids)
    else:
        form = EventForm()

    return render(request, 'organizer_create_event.html', {
        'form': form,
        'event_categories': event_categories,
        'attendees': attendees,  # Pass the attendees to the template context
        'active_page': 'events'  # Set the active_page context variable to 'events'
    })

def edit_event(request, event_id):
    # Retrieve existing event
    event = get_object_or_404(Event, id=event_id)

    if request.method == 'POST':
        # Handle form submission
        form = EditEventForm(request.POST, instance=event)
        if form.is_valid():
            form.save()

    else:
        # Pre-populate form fields with event data
        form = EditEventForm(instance=event)

    # Pass 'active_page' context variable
    context = {'form': form, 'event': event, 'active_page': 'events'}
    return render(request, 'organizer_edit_event.html', context)

def delete_event(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    event.delete()
    return redirect('event_organizer:organizer_events')  # Redirect to the events page after deletion

# Function to retrieve attendees
def attendees_view(request):
    # Retrieve the logged-in event organizer
    logged_in_organizer = request.user

    # Retrieve all attendees for events organized by the logged-in organizer
    all_attendees = Attendee.objects.filter(event__organizer=logged_in_organizer)

    # Pass the attendees data to the template
    context = {
        'all_attendees': all_attendees,
        'active_page': 'attendees'
    }
    return render(request, 'organizer_attendees.html', context)

event_organizer/templates/create_event_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>EventSphere</title>
    <!-- Boxicons -->
    <link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <!-- My CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/create_base.css' %}" />
    {% block extra_css %}{% endblock %}
  </head>
  <body>
    <!-- SIDEBAR -->
    <section id="sidebar">
      <a href="#" class="brand">
        <i class="fa-solid fa-calendar-days"></i>
        <span class="text">EventSphere</span>
      </a>
      <ul class="side-menu top">
        <li class="{% if active_page == 'dashboard' %}active{% endif %}">
          <a href="{% url 'event_organizer:dashboard' %}">
            <i class="bx bxs-dashboard"></i>
            <span class="text">Dashboard</span>
          </a>
        </li>
        <li class="{% if active_page == 'events' %}active{% endif %}">
          <a href="{% url 'event_organizer:organizer_events' %}">
            <i class="bx bxs-calendar-event"></i>
            <span class="text">Events</span>
          </a>
        </li>
        <li class="{% if active_page == 'attendees' %}active{% endif %}">
          <a href="{% url 'event_organizer:attendees' %}">
            <i class="bx bxs-group"></i>
            <span class="text">Attendees</span>
          </a>
        </li>
      </ul>
      <ul class="side-menu">
        <li>
          <a href="#">
            <i class="bx bxs-cog"></i>
            <span class="text">Profile</span>
          </a>
        </li>
        <li>
          <a href="#" class="logout">
            <i class="bx bxs-log-out-circle"></i>
            <span class="text">Logout</span>
          </a>
        </li>
      </ul>
    </section>
    <!-- SIDEBAR -->

    <!-- CONTENT -->
    <section id="content">
      <!-- NAVBAR -->
      <nav>
        <i class="bx bx-menu"></i>
        {% if user.is_authenticated %}
        <a href="#" class="profile">
          <i class="bx bxs-user-circle"></i>
          {{ user.username }}
        </a>
        {% endif %}
      </nav>
      <!-- NAVBAR -->

      <!-- MAIN -->
      <main>{% block content %} {% endblock %}</main>
      <!-- MAIN -->
    </section>
    <!-- CONTENT -->

    {% block extra_js %}
    <script src="{% static 'js/organizer_dashboard.js' %}"></script>
    {% endblock %}
  </body>
</html>

event_organizer/templates/edit_event_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>EventSphere</title>
    <!-- Boxicons -->
    <link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <!-- My CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/edit_event_base.css' %}" />
    {% block extra_css %}{% endblock %}
  </head>
  <body>
    <!-- SIDEBAR -->
    <section id="sidebar">
      <a href="#" class="brand">
        <i class="fa-solid fa-calendar-days"></i>
        <span class="text">EventSphere</span>
      </a>
      <ul class="side-menu top">
        <li class="{% if active_page == 'dashboard' %}active{% endif %}">
          <a href="{% url 'admin_panel:dashboard' %}">
            <i class="bx bxs-dashboard"></i>
            <span class="text">Dashboard</span>
          </a>
        </li>
        <li class="{% if active_page == 'events' %}active{% endif %}">
          <a href="{% url 'admin_panel:events' %}">
            <i class="bx bxs-calendar-event"></i>
            <span class="text">Events</span>
          </a>
        </li>
        <li class="{% if active_page == 'event_categories' %}active{% endif %}">
          <a href="{% url 'admin_panel:event_categories' %}">
            <i class="bx bxs-category"></i>
            <span class="text">Event Categories</span>
          </a>
        </li>
        <li class="{% if active_page == 'users' %}active{% endif %}">
          <a href="{% url 'admin_panel:users' %}">
            <i class="bx bxs-user"></i>
            <span class="text">Users</span>
          </a>
        </li>
        <li class="{% if active_page == 'event_organizers' %}active{% endif %}">
          <a href="{% url 'admin_panel:event_organizers' %}">
            <i class="bx bxs-group"></i>
            <span class="text">Event Organizers</span>
          </a>
        </li>
      </ul>
      <ul class="side-menu">
        <li>
          <a href="#">
            <i class="bx bxs-cog"></i>
            <span class="text">Settings</span>
          </a>
        </li>
        <li>
          <a href="#" class="logout">
            <i class="bx bxs-log-out-circle"></i>
            <span class="text">Logout</span>
          </a>
        </li>
      </ul>
    </section>
    <!-- SIDEBAR -->

    <!-- CONTENT -->
    <section id="content">
      <!-- NAVBAR -->
      <nav>
        <i class="bx bx-menu"></i>
        {% if user.is_authenticated %}
        <a href="#" class="profile">
          <i class="bx bxs-user-circle"></i>
          {{ user.username }}
        </a>
        {% endif %}
      </nav>
      <!-- NAVBAR -->

      <!-- MAIN -->
      <main>{% block content %} {% endblock %}</main>
      <!-- MAIN -->
    </section>
    <!-- CONTENT -->

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% block extra_js %}
    <script src="{% static 'js/admin_dashboard.js' %}"></script>
    {% endblock %}
  </body>
</html>

event_organizer/templates/organizer_attendees.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>EventSphere</title>

    <!-- Boxicons -->
    <link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <!-- My CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/organizer_attendee.css' %}" />
  </head>
  <body>
    <!-- SIDEBAR -->
    <section id="sidebar">
      <a href="#" class="brand">
        <i class="fa-solid fa-calendar-days"></i>
        <span class="text">EventSphere</span>
      </a>
      <ul class="side-menu top">
        <li class="{% if active_page == 'dashboard' %}active{% endif %}">
          <a href="{% url 'event_organizer:dashboard' %}">
            <i class="bx bxs-dashboard"></i>
            <span class="text">Dashboard</span>
          </a>
        </li>
        <li class="{% if active_page == 'events' %}active{% endif %}">
          <a href="{% url 'event_organizer:organizer_events' %}">
            <i class="bx bxs-calendar-event"></i>
            <span class="text">Events</span>
          </a>
        </li>
        <li class="{% if active_page == 'attendees' %}active{% endif %}">
          <a href="{% url 'event_organizer:attendees' %}">
            <i class="bx bxs-group"></i>
            <span class="text">Attendees</span>
          </a>
        </li>
      </ul>
      <ul class="side-menu">
        <li>
          <a href="#">
            <i class="bx bxs-cog"></i>
            <span class="text">Profile</span>
          </a>
        </li>
        <li>
          <a href="#" class="logout">
            <i class="bx bxs-log-out-circle"></i>
            <span class="text">Logout</span>
          </a>
        </li>
      </ul>
    </section>
    <!-- SIDEBAR -->

    <!-- CONTENT -->
    <section id="content">
      <!-- NAVBAR -->
      <nav>
        <i class="bx bx-menu"></i>
        {% if user.is_authenticated %}
        <a href="#" class="profile">
          <i class="bx bxs-user-circle"></i>
          {{ user.username }}
        </a>
        {% endif %}
      </nav>
      <!-- NAVBAR -->

      <!-- MAIN -->
      {% block content %}
      <main>
        <div class="table-data">
          <div class="attendees">
            <div class="head">
              <h3>Attendees</h3>
            </div>
            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Phone Number</th>
                  <th>Event Registered</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {% for attendee in all_attendees %}
                <tr>
                  <td>{{ attendee.name }}</td>
                  <td>{{ attendee.attendee.email }}</td>
                  <td>{{ attendee.phone_number }}</td>
                  <td>{{ attendee.event.name }}</td>
                  <td>
                    <button
                      class="status-btn {% if attendee.status == 'not_attended' %}not-attended{% else %}attended{% endif %}"
                    >
                      {{ attendee.get_status_display }}
                    </button>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </main>
      {% endblock %}
      <!-- MAIN -->
    </section>
    <!-- CONTENT -->

    {% block extra_js %}
    <script src="{% static 'js/organizer_dashboard.js' %}"></script>
    {% endblock %}
  </body>
</html>

event_organizer/templates/organizer_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>EventSphere</title>

    <!-- Boxicons -->
    <link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <!-- My CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/organizer_base.css' %}" />
  </head>
  <body>
    <!-- SIDEBAR -->
    <section id="sidebar">
      <a href="#" class="brand">
        <i class="fa-solid fa-calendar-days"></i>
        <span class="text">EventSphere</span>
      </a>
      <ul class="side-menu top">
        <li class="{% if active_page == 'dashboard' %}active{% endif %}">
          <a href="{% url 'event_organizer:dashboard' %}">
            <i class="bx bxs-dashboard"></i>
            <span class="text">Dashboard</span>
          </a>
        </li>
        <li class="{% if active_page == 'events' %}active{% endif %}">
          <a href="{% url 'event_organizer:organizer_events' %}">
            <i class="bx bxs-calendar-event"></i>
            <span class="text">Events</span>
          </a>
        </li>
        <li class="{% if active_page == 'attendees' %}active{% endif %}">
          <a href="{% url 'event_organizer:attendees' %}">
            <i class="bx bxs-group"></i>
            <span class="text">Attendees</span>
          </a>
        </li>
      </ul>
      <ul class="side-menu">
        <li>
          <a href="#">
            <i class="bx bxs-cog"></i>
            <span class="text">Profile</span>
          </a>
        </li>
        <li>
          <a href="#" class="logout">
            <i class="bx bxs-log-out-circle"></i>
            <span class="text">Logout</span>
          </a>
        </li>
      </ul>
    </section>
    <!-- SIDEBAR -->

    <!-- CONTENT -->
    <section id="content">
      <!-- NAVBAR -->
      <nav>
        <i class="bx bx-menu"></i>
        {% if user.is_authenticated %}
        <a href="#" class="profile">
          <i class="bx bxs-user-circle"></i>
          {{ user.username }}
        </a>
        {% endif %}
      </nav>
      <!-- NAVBAR -->

      <!-- MAIN -->
      {% block content %}
      <main>
        <div class="head-title">
          <div class="left">
            <h1>Dashboard</h1>
            <ul class="breadcrumb">
              <li>
                <a href="#">Dashboard</a>
              </li>
              <li><i class="bx bx-chevron-right"></i></li>
              <li>
                <a class="active" href="#">Home</a>
              </li>
            </ul>
          </div>
        </div>
        <ul class="box-info">
          <li>
            <i class="bx bxs-calendar-event"></i>
            <span class="text">
              <h3>{{ total_events }}</h3>
              <p>Events</p>
            </span>
          </li>
          <li>
            <i class="bx bxs-group"></i>
            <span class="text">
              <h3>{{ total_attendees}}</h3>
              <p>Total Attendees</p>
            </span>
          </li>
          <li>
            <i class="bx bxs-check-square"></i>
            <span class="text">
              <h3>{{ total_completed_events }}</h3>
              <p>Completed Events</p>
            </span>
          </li>
        </ul>

        <div class="table-data">
          <div class="events">
            <div class="head">
              <h3>Events</h3>
              <input type="text" id="search-input" placeholder="Search..." />
              <select id="filter-select">
                <option value="">All</option>
                <option value="department">Department Events</option>
                <option value="college">College Events</option>
                <option value="workshops">Workshops</option>
              </select>
              <button id="clear-filter">Clear Filter</button>
            </div>
            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Event Category</th>
                  <th>Location</th>
                  <th>Date</th>
                  <th>Ticket Type</th>
                  <th>Ticket Price</th>
                </tr>
              </thead>
              <tbody>
                {% for event in latest_events %}
                <tr>
                  <td>{{ event.name }}</td>
                  <td>{{ event.description }}</td>
                  <td>{{ event.event_category.name }}</td>
                  <td>{{ event.location }}</td>
                  <td>{{ event.date_time }}</td>
                  <td>{{ event.ticket_type }}</td>
                  <td>{{ event.ticket_price }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </main>
      {% endblock %}
      <!-- MAIN -->
    </section>
    <!-- CONTENT -->

    {% block extra_js %}
    <script src="{% static 'js/organizer_dashboard.js' %}"></script>
    {% endblock %}
  </body>
</html>

event_organizer/templates/organizer_create_event.html
{% extends "create_event_base.html" %} {% load static %} {% block content %}
<div class="create-event">
  <h3>Create Event</h3>

  <!-- Display messages -->
  <form
    id="create-event-form"
    method="post"
    enctype="multipart/form-data"
    action="{% url 'event_organizer:create_event' %}"
  >
    {% csrf_token %}
    <div class="form-group">
      <label for="name">Event Name:</label>
      <div class="input-field">
        <input type="text" id="name" name="name" required />
      </div>
    </div>
    <div class="form-group">
      <label for="description">Description:</label>
      <div class="input-field">
        <textarea id="description" name="description" required></textarea>
      </div>
    </div>
    <div class="form-group">
      <label for="event_category">Event Category:</label>
      <div class="input-field">
        <select id="event_category" name="event_category" required>
          {% for category in event_categories %}
          <option value="{{ category.id }}">{{ category.name }}</option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="form-group">
      <label for="location">Location:</label>
      <div class="input-field">
        <input type="text" id="location" name="location" required />
      </div>
    </div>
    <div class="form-group">
      <label for="date_time">Date:</label>
      <div class="input-field">
        <input type="datetime-local" id="date_time" name="date_time" required />
      </div>
    </div>
    <div class="form-group">
      <label for="image">Image:</label>
      <div class="input-field">
        <input type="file" id="image" name="image" accept="image/*" />
      </div>
    </div>
    <div class="form-group">
      <label for="ticket_type">Registration Type:</label>
      <div class="input-field">
        <select id="ticket_type" name="ticket_type" required>
          <option value="General">General</option>
          <option value="VIP">VIP</option>
          <!-- Add more options as needed -->
        </select>
      </div>
    </div>

    <div class="form-group">
      <label for="ticket_price">Registration Fee:</label>
      <div class="input-field">
        <input
          type="number"
          id="ticket_price"
          name="ticket_price"
          step="0.01"
          required
        />
      </div>
    </div>
    <button type="submit" id="submit-btn">Create</button>
  </form>
</div>
{% endblock %}

event_organizer/templates/organizer_edit_event.html
{% extends "create_event_base.html" %} {% load static%}{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/edit_event.css' %}" />
{% endblock %}{% block content %}
<div class="edit-event">
  <h3>Edit Event</h3>
  <form
    id="edit-event-form"
    method="post"
    enctype="multipart/form-data"
    action="{% url 'event_organizer:edit_event' event.id %}"
  >
    {% csrf_token %} {% for field in form %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field }}
    </div>
    {% endfor %}

    <button type="submit" id="submit-btn">Update</button>
  </form>
</div>
{% endblock %} {% block extra_js %}
<script src="{% static 'js/admin_dashboard.js' %}"></script>
{% endblock %}

event_organizer/templates/organizer_events.html
{% extends 'organizer_base.html' %} {% load static %} {% block content %}
<main>
  <div class="table-data">
    <div class="events">
      <div class="head">
        <h3>Events</h3>
        <a
          href="{% url 'event_organizer:create_event' %}"
          class="btn-create-event"
        >
          <i class="bx bxs-plus-circle"></i> Create Event</a
        >
      </div>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Event Organizer</th>
            <th>Event Category</th>
            <th>Location</th>
            <th>Date</th>
            <th>Ticket Type</th>
            <th>Ticket Price</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for event in all_events %}
          <tr>
            <td>{{ event.name }}</td>
            <td>{{ event.description }}</td>
            <td>{{ event.organizer }}</td>
            <td>{{ event.event_category }}</td>
            <td>{{ event.location }}</td>
            <td>{{ event.date_time }}</td>
            <td>{{ event.ticket_type }}</td>
            <td>{{ event.ticket_price }}</td>
            <td>
              <a
                href="{% url 'event_organizer:edit_event' event.id %}"
                class="action-btn"
                title="Edit"
              >
                <i class="bx bx-edit"></i>
              </a>
              <a
                href="{% url 'event_organizer:event_delete' event.id %}"
                class="action-btn"
                title="Delete"
              >
                <i class="bx bx-trash"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>
{% endblock %}