accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('registration/', views.registration_view, name='registration'),
    
    # Add other URLs for admin, organizer, and attendee dashboards
]

attendee/urls.py
from django.urls import path
from . import views

app_name = 'attendee'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('create_event_organizer/', views.event_organizer_form, name='create_event_organizer'),
    path('events/', views.events_list, name='events_list'),
    path('events/<int:event_id>/', views.event_detail, name='event_details'),
     path('generate_ticket/<int:event_id>/', views.generate_pdf, name='generate_ticket'),
    path('registration/', views.registration_view, name='registration'),
    ]

eventsphere/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_panel/', include('admin_panel.urls')),
    path('accounts/', include('accounts.urls')),
    path('event_organizer/', include('event_organizer.urls')),
    path('eventsphere/', include('attendee.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

attendee/models.py
from django.db import models
from django.conf import settings
from admin_panel.models import Event as AdminPanelEvent

class Ticket(models.Model):
    event = models.ForeignKey(AdminPanelEvent, on_delete=models.CASCADE)
    attendee = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='tickets_attendee')
    qr_code = models.ImageField(upload_to='qr_codes/')
    ticket_type = models.CharField(max_length=100)
    ticket_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Ticket {self.id} - {self.ticket_type}"

attendee/forms.py
from django import forms

class EventOrganizerForm(forms.Form):
    full_name = forms.CharField(max_length=100)
    email = forms.EmailField()
    phone_number = forms.CharField(max_length=15)
    college_name = forms.CharField(max_length=100)
    department = forms.CharField(max_length=100)
    additional_notes = forms.CharField(widget=forms.Textarea,required=False)

attendee/views.py
from django.shortcuts import render,get_object_or_404,redirect
from admin_panel.models import Event,EventCategory
from django.core.mail import send_mail
from django.utils import timezone
from .forms import EventOrganizerForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.http import HttpResponse
from django.views import View
from .models import Ticket
from admin_panel.models import Event as AdminPanelEvent
import qrcode
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from io import BytesIO
from PIL import Image 
from reportlab.lib import colors
from event_organizer.models import Attendee



def home(request):
    latest_events = Event.objects.filter(date_time__gte=timezone.now()).order_by('-date_time')[:4]
    active_link = 'home'
    context = {
        'latest_events': latest_events,
        'active_link': active_link,
    }
    return render(request, 'home.html', context)

def event_organizer_form(request):
    if request.method == 'POST':
        form = EventOrganizerForm(request.POST)
        if form.is_valid():
            # Get form data
            full_name = form.cleaned_data['full_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            college_name = form.cleaned_data['college_name']
            department = form.cleaned_data['department']
            additional_notes = form.cleaned_data['additional_notes']
            
            # Send email to admin
            send_mail(
                'New Event Organizer Request',
                f'Name: {full_name}\nEmail: {email}\nPhone: {phone_number}\nCollege: {college_name}\nDepartment: {department}\nNotes: {additional_notes}',
                'your_email@example.com',
                ['admin@example.com'],
                fail_silently=False,
            )
            # Redirect to a success page or show a success message
            return render(request, 'success.html')
    else:
        form = EventOrganizerForm()
    return render(request, 'create_event_organizer.html', {'form': form})

def events_list(request):
    all_events = Event.objects.all()  
    categories = EventCategory.objects.all()
    active_link = 'events'
    context = {
        'all_events': all_events,
        'categories': categories,
        'active_link': active_link,
    }
    return render(request, 'events_list.html', context)

def event_detail(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    active_link = 'events'

    context = {
        'event': event,
        'active_link': active_link,
    }
    return render(request, 'event_detail.html', context)

def generate_pdf(request, event_id):
    # Retrieve form data from request
    try:
        event_id = int(event_id)
    except ValueError:
        return HttpResponse("Invalid event ID", status=400)

    name = request.POST.get('name')
    gender = request.POST.get('gender')
    phone_number = request.POST.get('phone_number')
    user_role = request.POST.get('user_role')
    event_name = request.POST.get('event_name')
    event_price = request.POST.get('event_price')
    total_price = request.POST.get('total_price')
    quantity = request.POST.get('quantity')

    # Error checking for form fields
    if not name or not gender or not phone_number or not user_role or not event_name or not event_price or not total_price or not quantity:
        return HttpResponse("Missing form fields", status=400)

    try:
        event_price = float(event_price.replace('₹', '').strip())
        total_price = float(total_price.replace('₹', '').strip())
        quantity = int(quantity)
    except ValueError:
        return HttpResponse("Invalid form field values", status=400)

    # Retrieve the corresponding event
    event = get_object_or_404(AdminPanelEvent, id=event_id)

    # Save attendee information to the database
    for _ in range(quantity):
        ticket = Ticket.objects.create(
            event=event,
            attendee=request.user,
            ticket_type=event.ticket_type,
            ticket_price=event.ticket_price
        )

    # Update or create Attendee record
    attendee, created = Attendee.objects.update_or_create(
        attendee=request.user,
        event=event,
        defaults={'phone_number': phone_number, 'name': name}
    )
    if created:
        attendee.status = 'not_attended'  # Set initial status
        attendee.save()
    else:  # Update name and phone number if attendee already exists
        attendee.name = name
        attendee.phone_number = phone_number
        attendee.save()

    # Generate QR Codes for each attendee
    qr_codes = []
    for i in range(quantity):
        attendee_data = f"Name: {name}\nGender: {gender}\nPhone Number: {phone_number}\nUser Role: {user_role}\nEvent Name: {event_name}\nEvent Price: {event_price}\nTotal Price: {total_price}\nAttendee: {i+1}"
        qr = qrcode.make(attendee_data)
        qr_code_buffer = BytesIO()
        qr.save(qr_code_buffer, format="PNG")
        qr_code_buffer.seek(0)
        qr_codes.append(qr_code_buffer)

    # Generate PDF document
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="registration_details.pdf"'

    # Create PDF content
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)

    # Add border
    border_padding = 20
    border_width = letter[0] - 2 * border_padding
    border_height = letter[1] - 2 * border_padding
    p.setStrokeColor(colors.black)
    p.rect(border_padding, border_padding, border_width, border_height)

    # Add form details to PDF
    left_margin = 50
    y_position = letter[1] - 50  # Start from the top
    p.drawString(left_margin, y_position, f"Name: {name}")
    y_position -= 20
    p.drawString(left_margin, y_position, f"Gender: {gender}")
    y_position -= 20
    p.drawString(left_margin, y_position, f"Phone Number: {phone_number}")
    y_position -= 20
    p.drawString(left_margin, y_position, f"User Role: {user_role}")
    y_position -= 20
    p.drawString(left_margin, y_position, f"Event Name: {event_name}")
    y_position -= 20
    p.drawString(left_margin, y_position, f"Event Price: {event_price}")
    y_position -= 20
    p.drawString(left_margin, y_position, f"Total Price: {total_price}")

    # Add space between details and QR codes
    y_position -= 40

    qr_code_width = 100
    qr_code_height = 100
    right_margin = letter[0] - 50 - qr_code_width
    qr_code_x_position = right_margin 
    qr_code_y_position = letter[1] - 50 - qr_code_height 


    # Adjust the spacing between QR codes based on their number
    qr_code_spacing = (letter[1] - 100) / quantity if quantity > 1 else 0

    # Adjust the vertical spacing to ensure QR codes fit within the page
    if qr_code_y_position - (qr_code_height * quantity) - (qr_code_spacing * (quantity - 1)) < 50:
        qr_code_y_position = letter[1] - 50 - qr_code_height


    # Add QR codes to PDF
    qr_code_index = 0
    while qr_code_index < len(qr_codes):
        if qr_code_y_position - qr_code_height < 50:  # Check if enough space for another QR code
            p.showPage()  # Start a new page
            p.setStrokeColor(colors.black)
            p.rect(border_padding, border_padding, border_width, border_height)  # Add border
            qr_code_y_position = letter[1] - 50 - qr_code_height  # Reset vertical position

        qr_code = qr_codes[qr_code_index]
        qr_code.seek(0)
        pil_image = Image.open(qr_code)
        qr_code_image = BytesIO()
        pil_image.save(qr_code_image, format='PNG')
        qr_code_image.seek(0)
        p.drawInlineImage(Image.open(qr_code_image), qr_code_x_position, qr_code_y_position, width=qr_code_width, height=qr_code_height)
        qr_code_y_position -= qr_code_height + 20  # Adjust the vertical position for the next QR code
        qr_code_index += 1

    p.save()

    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)

    return response

def registration_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('attendee:events_list') 
    else:
        form = UserCreationForm()
    return render(request, 'registration.html', {'form': form})

attendee/templates/create_event_organizer.html
{% extends 'user_base.html' %} {% load static %} {% block content %}
    <section>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_full_name">Full Name</label>
          {{ form.full_name }}
        </div>
        <div class="form-group">
          <label for="id_email">Email Address</label>
          {{ form.email }}
        </div>
        <div class="form-group">
          <label for="id_phone_number">Phone Number</label>
          {{ form.phone_number }}
        </div>
        <div class="form-group">
          <label for="id_college_name">College Name</label>
          {{ form.college_name }}
        </div>
        <div class="form-group">
          <label for="id_department">Department</label>
          {{ form.department }}
        </div>
        <div class="form-group">
          <label for="id_additional_notes">Additional Notes</label>
          {{ form.additional_notes }}
        </div>
        <button type="submit" class="btn">Submit</button>
      </form>
      </section>
    
    {% endblock %}
  </body>
</html>

attendee/templates/event_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/event_detail.css' %}" />
    <title>EventSphere</title>
  </head>
  <body>
    <nav>
      <div class="nav__header">
        <div class="brand">
          <a href="#">
            <i class="fa-solid fa-calendar-days"></i>
            <span>EventSphere</span>
          </a>
        </div>
        <div class="nav__links">
          <ul>
            <li><a href="{% url 'attendee:home' %}"  {% if active_link == 'home' %}class="active"{% endif %}>Home</a></li>
            <li><a href="{% url 'attendee:create_event_organizer' %}"  {% if active_link == 'create_events' %}class="active"{% endif %}>Create Event</a></li>
            <li><a href="{% url 'attendee:events_list' %}"  {% if active_link == 'events' %}class="active"{% endif %}>Events</a></li>
            <li><a href="#" {% if request.path == '/contact/' %}class="active"{% endif %}>Contact Us</a></li>
          </ul>
        </div>
        <div class="nav__btns">
          {% if user.is_authenticated %}
          <div class="user-profile">
            <i class="fas fa-user"></i>
            <span class="username-text">{{ user.username }}</span>
          </div>
          {% else %}
          <a
            href="{% url 'attendee:registration' %}"
            class="btn btn-signup-login"
            >Sign Up/Login</a
          >
          {% endif %}
        </div>
        <div class="nav__menu__btn">
          <i class="fas fa-bars"></i>
        </div>
      </div>
    </nav>
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-12 text-center">
          <img
            src="{{ event.image.url }}"
            alt="Event Image"
            class="img-fluid event-image"
          />
        </div>
      </div>
      <div class="row mt-5">
        <div class="col-md-8">
          <h1 class="event-name">{{ event.name }}</h1>
          <p class="event-description">{{ event.description }}</p>
        </div>
        <div class="col-md-4 d-flex flex-column justify-content-start">
          <div>
            <h3>Date and Time</h3>
            <p>{{ event.date_time }}</p>
            <h3>Location</h3>
            <p>{{ event.location }}</p>
          </div>
          <h3>Registration Fee</h3>
          <div class="ticket-type-box">
            <h4>{{ event.ticket_type }}</h4>
            <p>Price: ₹<span id="ticket-price">{{ event.ticket_price }}</span></p>
            <div class="quantity-control">
              <button class="btn btn-secondary btn-sm decrement-btn">-</button>
              <input type="number" id="quantity" class="quantity" min="0" value="0" />
              <button class="btn btn-secondary btn-sm increment-btn">+</button>
            </div>
            <p>Total Price: ₹<span id="total-price">0</span></p> 
          </div>
          <form id="registration-form" method="post" action="{% url 'attendee:generate_ticket' event.id %}" onsubmit="event.preventDefault(); showModal();">
            {% csrf_token %}
            <input type="hidden" id="registration_quantity" name="quantity" value="0" />
            <button type="submit" class="btn btn-primary register-btn">
              Register
            </button>
          </form>
        </div>
      </div>
    </div>

    <!-- Modal -->
<div class="modal fade" id="registrationModal" tabindex="-1" aria-labelledby="registrationModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="registrationModalLabel">Register for Event</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <div class="modal-body">
              <form id="modal-form" method="post" action="{% url 'attendee:generate_ticket' event.id %}">
                  {% csrf_token %}
                  <div class="form-group">
                      <label for="name">Name</label>
                      <input type="text" class="form-control" id="name" name="name" required>
                  </div>
                  <div class="form-group">
                      <label for="gender">Gender</label>
                      <select class="form-control" id="gender" name="gender" required>
                          <option value="male">Male</option>
                          <option value="female">Female</option>
                          <option value="other">Other</option>
                      </select>
                  </div>
                  <div class="form-group">
                      <label for="phone_number">Phone Number</label>
                      <input type="text" class="form-control" id="phone_number" name="phone_number" required>
                  </div>
                  <div class="form-group">
                      <label for="user_role">User Role</label>
                      <select class="form-control" id="user_role" name="user_role" required>
                          <option value="student">Student</option>
                          <option value="staff">Staff</option>
                      </select>
                  </div>
                  <div class="form-group">
                      <label for="event_name">Event Name</label>
                      <input type="text" class="form-control" id="event_name" name="event_name" value="{{ event.name }}" readonly>
                  </div>
                  <div class="form-group">
                      <label for="event_price">Event Price</label>
                      <input type="text" class="form-control" id="event_price" name="event_price" value="₹{{ event.ticket_price }}" readonly>
                  </div>
                  <div class="form-group">
                      <label for="total_price">Total Price</label>
                      <input type="text" class="form-control" id="total_price_modal" name="total_price" readonly>
                  </div>
                  <input type="hidden" id="modal_quantity" name="quantity">
                  <button type="submit" class="btn btn-primary centered-btn">Generate Ticket</button>
              </form>
          </div>
      </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>    <script src="{% static 'js/event_detail.js' %}"></script>
  </body>
</html>

attendee/templates/events_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    {% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/events_list.css' %}" />
    {% endblock %}
    <title>EventSphere</title>
  </head>
  <body>
    <nav>
      <div class="nav__header">
        <div class="brand">
          <a href="#">
            <i class="fa-solid fa-calendar-days"></i>
            <span>EventSphere</span>
          </a>
        </div>
        <div class="nav__links">
          <ul>
            <li><a href="{% url 'attendee:home' %}"  {% if active_link == 'home' %}class="active"{% endif %}>Home</a></li>
            <li><a href="{% url 'attendee:create_event_organizer' %}"  {% if active_link == 'create_events' %}class="active"{% endif %}>Create Event</a></li>
            <li><a href="{% url 'attendee:events_list' %}"  {% if active_link == 'events' %}class="active"{% endif %}>Events</a></li>
            <li><a href="#" {% if request.path == '/contact/' %}class="active"{% endif %}>Contact Us</a></li>
          </ul>
        </div>
        <div class="nav__btns">
          {% if user.is_authenticated %}
          <div class="user-profile">
            <i class="fas fa-user"></i>
            <span class="username-text">{{ user.username }}</span>
          </div>
          {% else %}
          <a
            href="{% url 'attendee:registration' %}"
            class="btn btn-signup-login"
            >Sign Up/Login</a
          >
          {% endif %}
        </div>
        <div class="nav__menu__btn">
          <i class="fas fa-bars"></i>
        </div>
      </div>
    </nav>

    <div class="container my-5">
      <div class="search-filter-container mb-4">
        <div class="search-box">
          <input
            type="text"
            class="form-control"
            placeholder="Search events..."
          />
        </div>
        <div class="filter-options">
          <select class="form-control" id="category-filter">
            <option value="">Filter by</option>
            {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
          </select>
        </div>
      </div>

      <section class="events-section">
        <div class="container">
          <h2 class="mb-4 text-center">All Events</h2>
          <div class="row">
            {% for event in all_events %}
            <div
              class="col-md-4 mb-4 event-card"
              data-category="{{ event.category.id }}"
            >
              <div class="card">
                <img
                  src="{{ event.image.url }}"
                  class="card-img-top"
                  alt="{{ event.name }}"
                />
                <div class="card-body text-center">
                  <h5 class="card-title mb-3">{{ event.name }}</h5>
                  <p class="card-text">
                    {{ event.description|truncatewords:15 }}
                  </p>
                  <a
                    href="{% url 'attendee:event_details' event.id %}"
                    class="btn btn-primary"
                    >View Details</a
                  >
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </section>
    </div>

    {% block extra_js %}
    <script>
      // Filter events by category
      document
        .getElementById("category-filter")
        .addEventListener("change", function () {
          const categoryId = this.value;
          const eventCards = document.querySelectorAll(".event-card");
          eventCards.forEach(function (card) {
            if (
              categoryId === "" ||
              card.getAttribute("data-category") === categoryId
            ) {
              card.style.display = "block";
            } else {
              card.style.display = "none";
            }
          });
        });
    </script>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

attendee/templates/home.html
{% extends 'user_base.html' %} {% block content %}
<section class="event-discovery-section">
  <div class="event-discovery-content">
    <h2>Discover Exciting Events Near You</h2>
    <h1>Explore EventSphere for Your Next Adventure</h1>
    <p>
      EventSphere is your gateway to discovering and participating in a wide
      range of exciting events happening in and around the College of
      Engineering, Guindy (CEG). Whether you're passionate about music, arts,
      technology, or any other interest, EventSphere has something for everyone.
      Join us today and explore the vibrant world of events!
    </p>
    <div class="event-discovery-buttons">
      <a href="{% url 'attendee:create_event_organizer' %}" class="explore-btn"
        >Become an Event Organizer</a
      >
      <a href="{% url 'attendee:events_list' %}" class="explore-btn"
        >Explore Events</a
      >
    </div>
  </div>
</section>

<section class="latest-events-section">
  <div class="container">
    <h2 class="mb-4 text-center">Latest Events</h2>
    <div class="row">
      {% for event in latest_events %}
      <div class="col-md-3 mb-4">
        <div class="card event-card">
          <img
            src="{{ event.image.url }}"
            class="card-img-top"
            alt="{{ event.name }}"
          />
          <div class="card-body text-center">
            <h5 class="card-title mb-3">{{ event.name }}</h5>
            <a
              href="{% url 'attendee:event_details' event.id %}"
              class="btn btn-primary"
              >View Details</a
            >
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class="row">
      <div class="wow fadeInUp col-md-4 col-sm-4" data-wow-delay="0.6s">
        <h2>About EventSphere</h2>
        <p>
          EventSphere: Where Moments Meet Passion. Discover and Engage with
          Vibrant Events Near You!
        </p>
      </div>
      <div class="wow fadeInUp col-md-4 col-sm-4" data-wow-delay="0.9s">
        <h2>Quick Links</h2>
        <ul>
          <li><a href="#">Events</a></li>
          <li><a href="#">Contact Us</a></li>
        </ul>
      </div>
      <div class="wow fadeInUp col-md-4 col-sm-4" data-wow-delay="1s">
        <h2>Follow us</h2>
        <ul class="social-icon">
          <li>
            <a href="#" class="fab fa-facebook" data-wow-delay="1s"></a>
          </li>
          <li>
            <a href="#" class="fa-brands fa-twitter" data-wow-delay="1.3s"></a>
          </li>
          <li>
            <a href="#" class="fa-brands fa-linkedin" data-wow-delay="1.6s"></a>
          </li>
        </ul>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-md-12 col-sm-12">
      <p class="copyright-text">Copyright &copy; 2024 EventSphere</p>
    </div>
  </div>
</footer>
{% endblock %}

attendee/templates/pdf_template.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Event Tickets</title>
    <style>
      body {
        font-family: Arial, sans-serif;
      }
      .ticket {
        border: 1px solid #000;
        margin-bottom: 20px;
        padding: 20px;
      }
      .qr-code {
        width: 100px;
        height: 100px;
      }
    </style>
  </head>
  <body>
    <h1>Event Tickets</h1>
    <p>Name: {{ name }}</p>
    <p>Gender: {{ gender }}</p>
    <p>Phone Number: {{ phone_number }}</p>
    <p>User Role: {{ user_role }}</p>
    <p>Event Name: {{ event_name }}</p>
    <p>Event Price: ₹{{ event_price }}</p>
    <p>Total Price: ₹{{ total_price }}</p>
    <h2>Tickets</h2>
    {% for ticket in tickets %}
    <div class="ticket">
      <p>Ticket ID: {{ ticket.id }}</p>
      <p>Ticket Type: {{ ticket.ticket_type }}</p>
      <p>Ticket Price: ₹{{ ticket.ticket_price }}</p>
      <img src="{{ ticket.qr_code.url }}" alt="QR Code" class="qr-code" />
    </div>
    {% endfor %}
  </body>
</html>

attendee/templates/user_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    {% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    {% endblock %}
    <title>EventSphere</title>
  </head>
  <body>
    <nav>
      <div class="nav__header">
        <div class="brand">
          <a href="#">
            <i class="fa-solid fa-calendar-days"></i>
            <span>EventSphere</span>
          </a>
        </div>
        <div class="nav__links">
          <ul>
            <li><a href="{% url 'attendee:home' %}"  {% if active_link == 'home' %}class="active"{% endif %}>Home</a></li>
            <li><a href="{% url 'attendee:create_event_organizer' %}"  {% if active_link == 'create_events' %}class="active"{% endif %}>Create Event</a></li>
            <li><a href="{% url 'attendee:events_list' %}"  {% if active_link == 'events' %}class="active"{% endif %}>Events</a></li>
            <li><a href="#" {% if request.path == '/contact/' %}class="active"{% endif %}>Contact Us</a></li>
          </ul>
        </div>
        <div class="nav__btns">
          {% if user.is_authenticated %}
          <div class="user-profile">
            <i class="fas fa-user"></i>
            <span class="username-text">{{ user.username }}</span>
          </div>
          {% else %}
          <a
            href="{% url 'attendee:registration' %}"
            class="btn btn-signup-login"
            >Sign Up/Login</a
          >
          {% endif %}
        </div>
        <div class="nav__menu__btn">
          <i class="fas fa-bars"></i>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>