accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('registration/', views.registration_view, name='registration'),
    
    # Add other URLs for admin, organizer, and attendee dashboards
]

admin_panel/urls.py
from django.urls import path
from . import views


app_name = 'admin_panel'

urlpatterns = [
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('events/', views.events_view, name='events'),
    path('events/create_event/', views.create_event, name='create_event'),
    path('events/<int:event_id>/edit_event/', views.edit_event_view, name='edit_event'),
    path('events/<int:event_id>/delete/', views.delete_event, name='event_delete'),
    path('event_categories/', views.event_categories_view, name='event_categories'), 
    path('event_categories/create_category/', views.create_category, name='create_category'),
    path('event_categories/<int:category_id>/edit_category/', views.edit_category, name='edit_category'),
    path('event_categories/<int:category_id>/delete_category/', views.delete_category, name='delete_category'),
    path('users/', views.users_view, name='users'),
    path('users/create_user/', views.create_user, name='create_user'),
    path('users/<int:user_id>/edit_user/', views.edit_user, name='edit_user'),
    path('users/<int:user_id>/delete_user/', views.delete_user, name='delete_user'),
    path('event_organizers/', views.event_organizers_view, name='event_organizers'),
    path('event_organizers/create_organizer/', views.create_organizer, name='create_organizer'),
    path('event_organizers/<int:organizer_id>/edit_organizer/', views.edit_organizer, name='edit_organizer'),
    path('event_organizers/<int:organizer_id>/delete_organizer/', views.delete_organizer, name='delete_organizer')
]

attendee/urls.py
from django.urls import path
from . import views

app_name = 'attendee'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('create_event_organizer/', views.event_organizer_form, name='create_event_organizer'),
    path('events/', views.events_list, name='events_list'),
    path('events/<int:event_id>/', views.event_detail, name='event_details'),
     path('generate_ticket/<int:event_id>/', views.generate_pdf, name='generate_ticket'),
    path('registration/', views.registration_view, name='registration'),
    ]

eventsphere/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_panel/', include('admin_panel.urls')),
    path('accounts/', include('accounts.urls')),
    path('event_organizer/', include('event_organizer.urls')),
    path('eventsphere/', include('attendee.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin_panel/models.py
from django.db import models
from accounts.models import CustomUser
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField
from django.conf import settings

class EventCategory(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    total_events = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Event(models.Model):
    TICKET_TYPE_CHOICES = [
        ('VIP', 'VIP Ticket'),
        ('General', 'General Admission'),
    ]

    name = models.CharField(max_length=255)
    description = models.TextField()
    event_category = models.ForeignKey(EventCategory, on_delete=models.CASCADE)
    location = models.CharField(max_length=255)
    date_time = models.DateTimeField()
    image = models.ImageField(upload_to='event_images/', blank=False, null=True)
    organizer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    attendees = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='attended_events')
    ticket_type = models.CharField(max_length=100, choices=TICKET_TYPE_CHOICES,default='General')
    ticket_price = models.DecimalField(max_digits=10, decimal_places=2,default=0.00)

    def __str__(self):
        return self.name

    def is_completed(self):
        return self.date_time < timezone.now()

    @property
    def completed_events(self):
        return Event.objects.filter(date_time__lt=timezone.now())

class EventOrganizer(models.Model):
    STATUS_CHOICES = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected'),
    )
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    events_organized = models.ManyToManyField('admin_panel.Event', related_name='organizers', blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')
    phone_number = PhoneNumberField(blank=True)

    def __str__(self):
        return self.user.username

admin_panel/forms.py
from django import forms
from .models import Event,EventCategory,CustomUser,EventOrganizer

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'description', 'event_category', 'location', 'date_time', 'image','ticket_type', 'ticket_price']

class EditEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'description', 'event_category', 'location', 'date_time', 'image','ticket_type', 'ticket_price']
        widgets = {
            'date_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }
        labels = {
            'ticket_type': 'Registration Type',
            'ticket_price': 'Registration Fee',
        }

class EventCategoryForm(forms.ModelForm):
    class Meta:
        model = EventCategory
        fields = ['name', 'description']

class EditCategoryForm(forms.ModelForm):
    class Meta:
        model = EventCategory
        fields = ['name', 'description']  

    def __init__(self, *args, **kwargs):
        super(EditCategoryForm, self).__init__(*args, **kwargs)

class UserForm(forms.ModelForm):
    user_status = forms.ChoiceField(choices=CustomUser.USER_STATUS_CHOICES)

    class Meta:
        model = CustomUser
        fields = ['first_name', 'username', 'email', 'date_joined', 'user_type', 'user_status']
        widgets = {
            'date_joined': forms.DateInput(attrs={'type': 'date'})
        }


    def __init__(self, *args, **kwargs):
        queryset = kwargs.pop('queryset', Event.objects.none())  # Set a default empty queryset
        super().__init__(*args, **kwargs)

class EditUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'date_joined', 'user_type', 'user_status']
        widgets = {
            'date_joined': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        

class EventOrganizerForm(forms.ModelForm):
    events_organized = forms.ModelMultipleChoiceField(
        queryset=Event.objects.all(),
        required=False,
        widget=forms.SelectMultiple,
        label="Events Organized"
    )

    class Meta:
        model = EventOrganizer
        fields = ['phone_number', 'status', 'events_organized']

class EditOrganizerForm(forms.ModelForm):
    class Meta:
        model = EventOrganizer
        fields = ['phone_number', 'status', 'events_organized']
        widgets = {
            'events_organized': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(EditOrganizerForm, self).__init__(*args, **kwargs)
        self.fields['events_organized'].queryset = Event.objects.all()

admin_panel/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.db import transaction
from django.contrib.auth.decorators import login_required
from .models import Event, EventCategory, EventOrganizer
from accounts.models import CustomUser
from .forms import EventForm,EditEventForm,EventCategoryForm,EditCategoryForm,UserForm,EditUserForm,EventOrganizerForm,EditOrganizerForm
from django.utils import timezone
from django.contrib import messages
from django.urls import reverse
from django.http import JsonResponse
from django.contrib.auth import get_user_model
from django.views.generic import View
from .decorators import admin_required



# Views for Admin Dashboard
def dashboard_view(request):
    # Retrieve data for the dashboard
    total_events = Event.objects.count()
    total_categories = EventCategory.objects.count()
    total_organizers = EventOrganizer.objects.count()
    total_completed_events = Event.objects.filter(date_time__lt=timezone.now()).count()
    latest_events = Event.objects.order_by('-date_time')[:5]

    # Pass data to the template
    context = {
        'total_events': total_events,
        'total_categories': total_categories,
        'total_organizers': total_organizers,
        'total_completed_events': total_completed_events,
        'latest_events': latest_events,
        'active_page': 'dashboard'
    }
    return render(request, 'index.html',context)

# Function to retrieve event page
def events_view(request):
    all_events = Event.objects.all()
    return render(request, 'events.html', {'active_page': 'events', 'all_events': all_events})


def create_event(request):
    event_categories = EventCategory.objects.all()  # Retrieve all event categories
    attendees = CustomUser.objects.all()  # Retrieve all attendees
    
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.organizer = request.user  # Assign the authenticated user as the organizer
            event.save()
            form.save_m2m()
            
            # Handle attendees field
            attendee_ids = request.POST.getlist('attendees')
            event.attendees.set(attendee_ids)
            
            return redirect('admin_panel:events')  # Redirect to event detail page
    else:
        form = EventForm()

    return render(request, 'create_event.html', {
        'form': form,
        'event_categories': event_categories,
        'attendees': attendees,
        'active_page': 'events'
    })


def edit_event_view(request, event_id):
    # Retrieve existing event
    event = get_object_or_404(Event, id=event_id)

    if request.method == 'POST':
        # Handle form submission
        form = EditEventForm(request.POST, instance=event)
        if form.is_valid():
            form.save()

    else:
        # Pre-populate form fields with event data
        form = EditEventForm(instance=event)

    # Pass 'active_page' context variable
    context = {'form': form, 'event': event, 'active_page': 'events'}
    return render(request, 'edit_event.html', context)


def delete_event(request, event_id):
    event = get_object_or_404(Event, id=event_id)
    event.delete()
    return redirect('admin_panel:events')  # Redirect to the events page after deletion


# Function to retrieve event category page
def event_categories_view(request):
    all_categories = EventCategory.objects.all()
    return render(request, 'event_categories.html', {'active_page': 'event_categories', 'all_categories': all_categories})


def create_category(request):
    if request.method == 'POST':
        form = EventCategoryForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = EventCategoryForm()

    active_page = 'event_categories'
    return render(request, 'create_category.html', {'form': form, 'active_page': active_page})


def edit_category(request, category_id):
    category = get_object_or_404(EventCategory, id=category_id)
    if request.method == 'POST':
        form = EventCategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            # Redirect to a success page or another view
    else:
        form = EventCategoryForm(instance=category)
    active_page = 'event_categories'
    return render(request, 'edit_category.html', {'form': form, 'category': category, 'active_page': active_page})

  
def delete_category(request, category_id):
    category = get_object_or_404(EventCategory, id=category_id)
    category.delete()
    # Redirect to a success page or another appropriate URL
    return redirect('admin_panel:event_categories')


# Function to retrieve user page
def users_view(request):
    # Retrieve all CustomUser objects along with related data
    all_users = CustomUser.objects.all()

    context = {
        'active_page': 'users',  # Set active_page context variable
        'users': all_users,  # Pass the users data to the template
    }
    
    return render(request, 'attendees.html', context)


def create_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            if user.username:  # Ensure username is provided and not empty
                events_attending = form.cleaned_data.get('events_attending', [])
                user.save()
                user.events_attending.set(events_attending)
                success_message = 'User created successfully.'
                messages.success(request, success_message)
                return redirect('admin_panel:users')
            else:
                error_message = 'Username is required.'
                messages.error(request, error_message)
        else:
            error_message = 'Failed to create user. Please check the form data.'
            print(form.errors)  # Print form errors for debugging
            messages.error(request, error_message)
    else:
        queryset = Event.objects.all()  # Example queryset
        form = UserForm(queryset=queryset)  # Pass the queryset to the form

    context = {
        'form': form,
        'active_page': 'users',
    }
    return render(request, 'create_attendee.html', context)


def edit_user(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)

    if request.method == 'POST':
        form = EditUserForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            events_attending = form.cleaned_data.get('events_attending', [])
            user.save()
            user.events_attending.set(events_attending)
            success_message = 'User updated successfully.'
            messages.success(request, success_message)
            return redirect('admin_panel:users')
    else:
        form = EditUserForm(instance=user)

    context = {
        'form': form,
        'user': user,
        'active_page': 'users'
    }
    return render(request, 'edit_user.html', context)

def delete_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.delete()
    return redirect('admin_panel:users')


def event_organizers_view(request):
    active_page = None
    organizers_with_events = {}  # Initialize an empty dictionary to store organizers and their events
    organizers = EventOrganizer.objects.all()
    for organizer in organizers:
        # Retrieve events organized by the organizer
        events = organizer.events_organized.all()
        organizers_with_events[organizer] = events
        active_page = 'event_organizers'
    context = {
        'organizers_with_events': organizers_with_events,
        'active_page': active_page,
    }
    return render(request, 'event_organizers.html', context)

from django.http import JsonResponse

User = get_user_model()


def create_organizer(request):
    if request.method == 'POST':
        form = EventOrganizerForm(request.POST)
        if form.is_valid():
            # Create a new User instance
            user_data = {
                'username': request.POST.get('username'),
                'email': request.POST.get('email'),
                'first_name': request.POST.get('first_name'),
                'user_type': 'organizer',
            }
            user = User.objects.create_user(**user_data)

            # Create an Organizer instance and associate it with the User
            organizer = form.save(commit=False)
            organizer.user = user
            organizer.save()
            form.save_m2m()  # Save the many-to-many relationships

            return JsonResponse({'success': 'Organizer created successfully.'}, status=200)
        return JsonResponse({'error': form.errors}, status=400)

    else:
        form = EventOrganizerForm()
        active_page = 'event_organizers'
        return render(request, 'create_organizer.html', {'form': form, 'active_page': active_page})

          
def edit_organizer(request, organizer_id):
    organizer = get_object_or_404(EventOrganizer, id=organizer_id)

    if request.method == 'POST':
        form = EditOrganizerForm(request.POST, instance=organizer)
        if form.is_valid():
            form.save()
            organizer.phone_number = form.cleaned_data['phone_number']  # Update phone number
            organizer.save()
            return redirect('admin_panel:event_organizers')
    else:
        form = EditOrganizerForm(instance=organizer)

    active_page = 'event_organizers'
    context = {
        'form': form,
        'organizer': organizer,
        'active_page': active_page,
    }
    return render(request, 'edit_organizer.html', context)


def delete_organizer(request, organizer_id):
    organizer = get_object_or_404(EventOrganizer, id=organizer_id)
    organizer.delete()
    return redirect('admin_panel:event_organizers')

admin_panel/templates/attendees.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main>
  <!-- Content for events page -->

  <div class="table-data">
    <div class="events">
      <div class="head">
        <!-- Content for events page specific to the table header -->
        <h3>Users</h3>
        <a
          href="{% url 'admin_panel:create_user' %}"
          class="btn-create-attendee"
        >
          <i class="bx bxs-plus-circle"></i> Create User
        </a>
      </div>
      <table>
        <thead>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Date Joined</th>
            <th>User Type</th>
            <th>Events Registered</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
          <tr>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.date_joined|date:"Y-m-d" }}</td>
            <td>
              <button
                class="user-type-btn {% if user.user_type == 'admin' %}user-type-admin{% endif %} {% if user.user_type == 'attendee' %}user-type-attendee{% endif %} {% if user.user_type != 'admin' and user.user_type != 'attendee' %}user-type-default{% endif %}"
              >
                {{ user.user_type }}
              </button>
            </td>
            <td>
              {% if user.events_attending.exists %}
              <ul>
                {% for event in user.events_attending.all %}
                <li>{{ event.name }}</li>
                {% endfor %}
              </ul>
              {% else %}
              <i>Not Registered</i>
              {% endif %}
            </td>
            <td>
              <button
                class="status-btn {% if user.user_status == 'active' %}status-active{% else %}status-inactive{% endif %}"
              >
                {{ user.user_status }}
              </button>
            </td>
            <td>
              <!-- Action buttons for each event -->
              <a
                href="{% url 'admin_panel:edit_user' user.id %}"
                class="action-btn"
                title="Edit"
              >
                <i class="bx bx-edit"></i>
              </a>
              <a
                href="{% url 'admin_panel:delete_user' user.id %}"
                class="action-btn"
                title="Delete"
              >
                <i class="bx bx-trash"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>
{% endblock %}

admin_panel/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>EventSphere</title>

    <!-- Boxicons -->
    <link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <link
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <!-- My CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" />
    {% block extra_css %} {% endblock %}
  </head>
  <body>
    <!-- SIDEBAR -->
    <section id="sidebar">
      <a href="#" class="brand">
        <i class="fa-solid fa-calendar-days"></i>
        <span class="text">EventSphere</span>
      </a>
      <ul class="side-menu top">
        <li class="{% if active_page == 'dashboard' %}active{% endif %}">
          <a href="{% url 'admin_panel:dashboard' %}">
            <i class="bx bxs-dashboard"></i>
            <span class="text">Dashboard</span>
          </a>
        </li>
        <li class="{% if active_page == 'events' %}active{% endif %}">
          <a href="{% url 'admin_panel:events' %}">
            <i class="bx bxs-calendar-event"></i>
            <span class="text">Events</span>
          </a>
        </li>
        <li class="{% if active_page == 'event_categories' %}active{% endif %}">
          <a href="{% url 'admin_panel:event_categories' %}">
            <i class="bx bxs-category"></i>
            <span class="text">Event Categories</span>
          </a>
        </li>
        <li class="{% if active_page == 'users' %}active{% endif %}">
          <a href="{% url 'admin_panel:users' %}">
            <i class="bx bxs-user"></i>
            <span class="text">Users</span>
          </a>
        </li>
        <li class="{% if active_page == 'event_organizers' %}active{% endif %}">
          <a href="{% url 'admin_panel:event_organizers' %}">
            <i class="bx bxs-group"></i>
            <span class="text">Event Organizers</span>
          </a>
        </li>
      </ul>
      <ul class="side-menu">
        <li>
          <a href="#">
            <i class="bx bxs-cog"></i>
            <span class="text">Profile</span>
          </a>
        </li>
        <li>
          <a href="#" class="logout">
            <i class="bx bxs-log-out-circle"></i>
            <span class="text">Logout</span>
          </a>
        </li>
      </ul>
    </section>
    <!-- SIDEBAR -->

    <!-- CONTENT -->
    <section id="content">
      <!-- NAVBAR -->
      <nav>
        <i class="bx bx-menu"></i>
        {% if user.is_authenticated %}
        <a href="#" class="profile">
          <i class="bx bxs-user-circle"></i>
          {{ user.username }}
        </a>
        {% endif %}
      </nav>
      <!-- NAVBAR -->

      <!-- MAIN -->
      {% block content %} {% endblock %}
      <!-- MAIN -->
    </section>
    <!-- CONTENT -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block extra_js %}
    <script src="{% static 'js/admin_dashboard.js' %}"></script>
    {% endblock %}
  </body>
</html>

admin_panel/templates/create_attendee.html
{% extends "create_base.html" %} {% load static %} {% block content %}
<div class="create-event">
  <h3>Create User</h3>
  <form
    id="create-event-form"
    method="post"
    enctype="multipart/form-data"
    action="{% url 'admin_panel:create_user' %}"
  >
    {% csrf_token %} {% for field in form %}
    <div class="form-group">
      {{ field.label_tag }}
      <div class="input-field">
        {{ field }} {% if field.errors %}
        <div class="error">{{ field.errors }}</div>
        {% endif %}
      </div>
    </div>
    {% endfor %}
    <button type="submit" id="submit-btn">Create</button>
  </form>
</div>
{% endblock %}

admin_panel/templates/event_categories.html
{% extends 'base.html' %} {% load static %} {% block extra_css %}
<link rel="stylesheet" href="{% static 'css/sweetalert2.min.css' %}" />
{% endblock %}{% block content %}
<main>
  <!-- Content for event category page -->
  <div class="table-data">
    <div class="events">
      <div class="head">
        <!-- Content for event category page specific to the table header -->
        <h3>Event Categories</h3>
        <a
          href="{% url 'admin_panel:create_category' %}"
          class="btn-create-category"
        >
          <i class="bx bxs-plus-circle"></i> Create Category
        </a>
      </div>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Total Events</th>
            <th>Actions</th>
            <!-- Column for edit and delete actions -->
          </tr>
        </thead>
        <tbody>
          {% for category in all_categories %}
          <tr>
            <td>{{ category.name }}</td>
            <td>{{ category.description }}</td>
            <td>{{ category.event_set.count }}</td>
            <td>
              <!-- Edit option with tooltip -->
              <a
                href="{% url 'admin_panel:edit_category' category.id %}"
                class="action-btn"
                title="Edit"
              >
                <i class="bx bx-edit"></i>
              </a>
              <!-- Delete option with tooltip -->
              <a
                href="{% url 'admin_panel:delete_category' category.id %}"
                class="action-btn"
                title="Delete"
              >
                <i class="bx bx-trash"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>
{% endblock %}

admin_panel/templates/event_organizers.html
{% extends 'base.html' %} {% load static %}{% block content %}
<main>
  <!-- Content for event category page -->
  <div class="table-data">
    <div class="events">
      <div class="head">
        <!-- Content for event category page specific to the table header -->
        <h3>Event Organizers</h3>
        <a
          href="{% url 'admin_panel:create_organizer' %}"
          class="btn-create-organizer"
        >
          <i class="bx bxs-plus-circle"></i> Create Event Organizer
        </a>
      </div>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Username</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Status</th>
            <th>Event Organized</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for organizer, events in organizers_with_events.items %}
          <tr>
            <td>{{ organizer.user.first_name }}</td>
            <td>{{ organizer.user.username }}</td>
            <td>{{ organizer.user.email }}</td>
            <td>{{ organizer.phone_number }}</td>
            <td>
              {% if organizer.status == 'Pending' %}
              <button class="status-btn pending">Pending</button>
              {% elif organizer.status == 'Approved' %}
              <button class="status-btn approved">Approved</button>
              {% elif organizer.status == 'Rejected' %}
              <button class="status-btn rejected">Rejected</button>
              {% endif %}
            </td>
            <td>
              {% for event in events %} {{ event.name }}<br />
              {% endfor %}
            </td>
            <td>
              <!-- Edit option with tooltip -->
              <a
                href="{% url 'admin_panel:edit_organizer' organizer.id %}"
                class="action-btn"
                title="Edit"
              >
                <i class="bx bx-edit"></i>
              </a>
              <!-- Delete option with tooltip -->
              <a
                href="{% url 'admin_panel:delete_organizer' organizer.id %}"
                class="action-btn"
                title="Delete"
              >
                <i class="bx bx-trash"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>
{% endblock %} {% block extra_js %}
<script src="{% static 'js/admin_dashboard.js' %}"></script>
{% endblock %}

admin_panel/templates/events.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main>
  <div class="table-data">
    <div class="events">
      <div class="head">
        <h3>Events</h3>
        <a href="{% url 'admin_panel:create_event' %}" class="btn-create-event">
          <i class="bx bxs-plus-circle"></i> Create Event</a
        >
      </div>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Event Organizer</th>
            <th>Event Category</th>
            <th>Location</th>
            <th>Date</th>
            <th>Registration Type</th>
            <th>Registration Fee</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for event in all_events %}
          <tr>
            <td>{{ event.name }}</td>
            <td>{{ event.description }}</td>
            <td>{{ event.organizer }}</td>
            <td>{{ event.event_category }}</td>
            <td>{{ event.location }}</td>
            <td>{{ event.date_time }}</td>
            <td>{{ event.ticket_type }}</td>
            <td>₹{{ event.ticket_price }}</td>
            <td>
              <a
                href="{% url 'admin_panel:edit_event' event.id %}"
                class="action-btn"
                title="Edit"
              >
                <i class="bx bx-edit"></i>
              </a>
              <a
                href="{% url 'admin_panel:event_delete' event.id %}"
                class="action-btn delete-event"
                title="Delete"
              >
                <i class="bx bx-trash"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>
{% endblock %}